"""empty message

Revision ID: 174604a07edc
Revises: 72520bf936c6
Create Date: 2021-04-06 16:43:46.603165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '174604a07edc'
down_revision = '72520bf936c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('employer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'jobs', 'recruitment_organisation', ['employer_id'], ['id'])
    op.drop_column('jobs', 'employer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('employer', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'employer_id')
    # ### end Alembic commands ###
