"""empty message

Revision ID: 26b2060feb1e
Revises: 6283f9b363af
Create Date: 2020-11-09 14:24:45.440393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26b2060feb1e'
down_revision = '6283f9b363af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specialization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('jobs', 'specialization')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('specialization', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('specialization')
    # ### end Alembic commands ###
