"""empty message

Revision ID: 33b47f1249c0
Revises: 1af979f03503
Create Date: 2020-12-11 18:18:53.835630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33b47f1249c0'
down_revision = '1af979f03503'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thesis', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('thesis', 'description')
    # ### end Alembic commands ###
