"""empty message

Revision ID: 3fa3eb155f9f
Revises: 76df844724d1
Create Date: 2021-02-26 18:37:03.915291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fa3eb155f9f'
down_revision = '76df844724d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('smart_badges', sa.Column('oubadge', sa.JSON(), nullable=True))
    op.add_column('user_badge_relation', sa.Column('oubadge_user', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_badge_relation', 'oubadge_user')
    op.drop_column('smart_badges', 'oubadge')
    # ### end Alembic commands ###
