"""empty message

Revision ID: 439cc87f5843
Revises: 3470cd3f791c
Create Date: 2020-10-26 19:37:48.635092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '439cc87f5843'
down_revision = '3470cd3f791c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skills', sa.Column('type', sa.String(), nullable=True))
    op.drop_column('skills', 'description')
    op.drop_column('skills', 'alternative_labels')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skills', sa.Column('alternative_labels', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('skills', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('skills', 'type')
    # ### end Alembic commands ###
