"""empty message

Revision ID: 4c2ffeb16816
Revises: 677fdf12c149
Create Date: 2021-04-28 14:54:57.340509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c2ffeb16816'
down_revision = '677fdf12c149'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('solid_pod', sa.Boolean(), server_default='t', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'solid_pod')
    # ### end Alembic commands ###
