"""empty message

Revision ID: 5114a4d22ffc
Revises: 174604a07edc
Create Date: 2021-04-06 20:06:56.592221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5114a4d22ffc'
down_revision = '174604a07edc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('courses_academic_organisation_fkey', 'courses', type_='foreignkey')
    op.create_foreign_key(None, 'courses', 'academic_organisation', ['academic_organisation'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.create_foreign_key('courses_academic_organisation_fkey', 'courses', 'jobs', ['academic_organisation'], ['id'])
    # ### end Alembic commands ###
