"""empty message

Revision ID: 6283f9b363af
Revises: 439cc87f5843
Create Date: 2020-10-27 13:27:57.018527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6283f9b363af'
down_revision = '439cc87f5843'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skills', sa.Column('alt_label', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skills', 'alt_label')
    # ### end Alembic commands ###
