"""empty message

Revision ID: 677fdf12c149
Revises: 7445ab70c40a
Create Date: 2021-04-28 11:21:07.011968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '677fdf12c149'
down_revision = '7445ab70c40a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_app_sequence_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_sequence_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_sequence_table')
    op.drop_table('job_app_sequence_table')
    # ### end Alembic commands ###
