"""empty message

Revision ID: 7445ab70c40a
Revises: 5114a4d22ffc
Create Date: 2021-04-22 17:26:16.376336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7445ab70c40a'
down_revision = '5114a4d22ffc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('academic_organisation_id', sa.Integer(), nullable=True))
    op.drop_constraint('courses_academic_organisation_fkey', 'courses', type_='foreignkey')
    op.create_foreign_key(None, 'courses', 'academic_organisation', ['academic_organisation_id'], ['id'])
    op.drop_column('courses', 'academic_organisation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('academic_organisation', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.create_foreign_key('courses_academic_organisation_fkey', 'courses', 'academic_organisation', ['academic_organisation'], ['id'])
    op.drop_column('courses', 'academic_organisation_id')
    # ### end Alembic commands ###
