"""empty message

Revision ID: 77eafcb13780
Revises: a709582f1482
Create Date: 2021-02-25 18:16:22.867976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77eafcb13780'
down_revision = 'a709582f1482'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kpi_time',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kpi_name', sa.String(), nullable=True),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('thesis_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thesis_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['thesis_id'], ['thesis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user_notification_preference', sa.Column('internal_reallocation_availability', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_notification_preference', 'internal_reallocation_availability')
    op.drop_table('thesis_requests')
    op.drop_table('kpi_time')
    # ### end Alembic commands ###
