"""empty message

Revision ID: 8268880bacf0
Revises: 4c2ffeb16816
Create Date: 2021-05-05 16:18:00.265200

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8268880bacf0'
down_revision = '4c2ffeb16816'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'level_value')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('level_value', postgresql.ENUM('entry', 'intermediate', 'experienced', 'advanced', 'expert', name='joblevel'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
