"""empty message

Revision ID: 83beab9ed991
Revises: f036ab2b0546
Create Date: 2021-05-07 13:46:13.231898

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '83beab9ed991'
down_revision = 'f036ab2b0546'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('employment_type', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('level', sa.String(), nullable=True))
    op.drop_column('jobs', 'employment_value')
    op.drop_column('jobs', 'level_value')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('level_value', postgresql.ENUM('internership', 'associate', 'entry_level', 'director', 'intermediate', 'mid_senior_level', 'executive', 'experienced', 'advanced', 'expert', 'not_applicable', name='joblevel'), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('employment_value', postgresql.ENUM('part_time', 'full_time', 'contractor', 'freelance', 'volunteer', 'internship', 'temporary', 'contract', name='employmenttype'), autoincrement=False, nullable=True))
    op.drop_column('jobs', 'level')
    op.drop_column('jobs', 'employment_type')
    # ### end Alembic commands ###
