"""empty message

Revision ID: 890c6b3e3f7a
Revises: 83beab9ed991
Create Date: 2021-05-18 15:47:06.533538

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '890c6b3e3f7a'
down_revision = '83beab9ed991'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_courses', sa.Column('course_status', sa.String(), nullable=True))
    op.drop_column('user_courses', 'status_value')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_courses', sa.Column('status_value', postgresql.ENUM('enrolled', 'taught', 'done', name='coursestatus'), autoincrement=False, nullable=True))
    op.drop_column('user_courses', 'course_status')
    # ### end Alembic commands ###
