"""empty message

Revision ID: 96df4e739c2d
Revises: 8268880bacf0
Create Date: 2021-05-05 16:19:35.241644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96df4e739c2d'
down_revision = '8268880bacf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('level_value', sa.Enum('internership', 'associate', 'entry', 'director', 'intermediate', 'mid_senior_level', 'executive', 'experienced', 'advanced', 'expert', 'not_applicable', name='joblevel'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'level_value')
    # ### end Alembic commands ###
