"""empty message

Revision ID: 9d8e0a452567
Revises: 26b2060feb1e
Create Date: 2020-11-09 16:14:17.549337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d8e0a452567'
down_revision = '26b2060feb1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('specialization', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'jobs', 'specialization', ['specialization'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'specialization')
    # ### end Alembic commands ###
