"""empty message

Revision ID: bda4a774125d
Revises: 77eafcb13780
Create Date: 2021-03-05 21:54:00.757213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bda4a774125d'
down_revision = '77eafcb13780'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('smart_badges', sa.Column('oubadge', sa.JSON(), nullable=False))
    op.add_column('user_badge_relation', sa.Column('ou_metadata', sa.JSON(), nullable=True))
    op.add_column('user_badge_relation', sa.Column('oubadge_user', sa.JSON(), nullable=False))
    op.create_unique_constraint(None, 'user_badge_relation', ['badge_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_badge_relation', type_='unique')
    op.drop_column('user_badge_relation', 'oubadge_user')
    op.drop_column('user_badge_relation', 'ou_metadata')
    op.drop_column('smart_badges', 'oubadge')
    # ### end Alembic commands ###
