"""empty message

Revision ID: c10dca91fd4e
Revises: f2d58110c2b6
Create Date: 2021-09-24 13:30:01.620705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c10dca91fd4e'
down_revision = 'f2d58110c2b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_badge_relation', sa.Column('awarded_by_id', sa.Integer(), nullable=True))
    op.add_column('user_badge_relation', sa.Column('awarded_by_role', sa.String(), nullable=True))
    op.drop_constraint('user_badge_relation_badge_id_user_id_key', 'user_badge_relation', type_='unique')
    op.create_unique_constraint(None, 'user_badge_relation', ['badge_id', 'user_id', 'awarded_by_id'])
    op.create_foreign_key(None, 'user_badge_relation', 'users', ['awarded_by_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_badge_relation', type_='foreignkey')
    op.drop_constraint(None, 'user_badge_relation', type_='unique')
    op.create_unique_constraint('user_badge_relation_badge_id_user_id_key', 'user_badge_relation', ['badge_id', 'user_id'])
    op.drop_column('user_badge_relation', 'awarded_by_role')
    op.drop_column('user_badge_relation', 'awarded_by_id')
    # ### end Alembic commands ###
