"""empty message

Revision ID: d2ea5e6d084a
Revises: f37495b559a0
Create Date: 2021-02-26 23:12:43.798789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2ea5e6d084a'
down_revision = 'f37495b559a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user_badge_relation', ['badge_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_badge_relation', type_='unique')
    # ### end Alembic commands ###
