"""empty message

Revision ID: e2923a0d8d0d
Revises: 890c6b3e3f7a
Create Date: 2021-06-29 18:06:02.291988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2923a0d8d0d'
down_revision = '890c6b3e3f7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('end_date', sa.String(), nullable=True))
    op.add_column('courses', sa.Column('start_date', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'start_date')
    op.drop_column('courses', 'end_date')
    # ### end Alembic commands ###
