"""empty message

Revision ID: f036ab2b0546
Revises: 2fbf7fc17902
Create Date: 2021-05-05 16:38:55.154077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f036ab2b0546'
down_revision = '2fbf7fc17902'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('employment_value', sa.Enum('full_time', 'part_time', 'contractor', 'freelance', 'volunteer', 'internship', 'temporary', 'contract', name='employmenttype'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'employment_value')
    # ### end Alembic commands ###
