"""empty message

Revision ID: f2d58110c2b6
Revises: e2923a0d8d0d
Create Date: 2021-09-10 13:36:36.488366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2d58110c2b6'
down_revision = 'e2923a0d8d0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_notification_preference', sa.Column('organisation', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_notification_preference', 'recruitment_organisation', ['organisation'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_notification_preference', type_='foreignkey')
    op.drop_column('user_notification_preference', 'organisation')
    # ### end Alembic commands ###
