"""empty message

Revision ID: f37495b559a0
Revises: def3aec9218f
Create Date: 2021-02-26 22:18:55.914634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f37495b559a0'
down_revision = 'def3aec9218f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_badge_relation', sa.Column('ou_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_badge_relation', 'ou_metadata')
    # ### end Alembic commands ###
