version: '3.4'

services:

  q_mediator_api:
    container_name: q_mediator_api
    hostname: q_mediator_api
    restart: always
    build:
      context: ".."
      dockerfile: config/Dockerfile
    environment:
      API_PORT: 5000
      RABBITMQ_HOST: ${RABBITMQ_IP}
      FUSEKI_CLIENT_HOST: ${FUSEKI_IP}

    networks:
      - config_qmediator
    ports:
    - 5000:5000


networks:
  config_qmediator:
    external: true


