version: '3.4'

volumes:
  mediator_api_db:

services:

  mediator_api_db:
    image: postgres:10
    hostname: ${DB_HOSTNAME}
    container_name: ${DB_HOSTNAME}
    restart: always
    ports:
      - 5432:5432
    volumes:
      - mediator_api_db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - config_qmediator

  q_mediator_api:
    container_name: ${API_HOSTNAME}
    hostname: ${API_HOSTNAME}
    restart: always
    build:
      context: ".."
      dockerfile: config/Dockerfile
    environment:
      API_PORT: ${API_PORT}
      RABBITMQ_HOST: ${RABBITMQ_IP}
      FUSEKI_CLIENT_HOST: ${FUSEKI_IP}

      POSTGRES_HOST: ${DB_HOSTNAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    depends_on:
      - mediator_api_db
    networks:
      - config_qmediator
    ports:
    - 5000:5000


networks:
  config_qmediator:
    external: true


