version: '3.4'

volumes:
  qualichain_db:

services:

  qualichain_db:
    image: postgres:10
    hostname: ${DB_HOSTNAME}
    container_name: ${DB_HOSTNAME}
    restart: always
    command: ["-c", "shared_buffers=3GB", "-c", "max_connections=1000", "-c", "idle_in_transaction_session_timeout=1min"]
    ports:
      - 5435:5432
    volumes:
      - qualichain_db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - config_qmediator

  qualichain_backend:
    container_name: ${API_HOSTNAME}
    hostname: ${API_HOSTNAME}
    restart: always
    build:
      context: ".."
      dockerfile: config/Dockerfile
    environment:
      API_PORT: ${API_PORT}
      RABBITMQ_HOST: ${RABBITMQ_IP}
      FUSEKI_CLIENT_HOST: ${FUSEKI_IP}

      POSTGRES_HOST: ${DB_HOSTNAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRESS_PORT: ${POSTGRESS_PORT}

      CDB_USER: ${CDB_USER}
      CDB_PASSWORD: ${CDB_PASSWORD}
      CDB_HOST: ${CDB_HOST}
      CDB_DATABASE: ${CDB_DATABASE}

      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_SERVER: ${MAIL_SERVER}
    ports:
    - 5004:5000
    depends_on:
      - qualichain_db
    networks:
      - config_qmediator

  qualichain_async:
    container_name: ${QC_BEAT_HOSTNAME}
    hostname: ${QC_BEAT_HOSTNAME}
    restart: always
    command: "celery -A tasks worker -B -l info"
    build:
      context: ".."
      dockerfile: config/Dockerfile
    environment:
      API_PORT: ${API_PORT}
      RABBITMQ_HOST: ${RABBITMQ_IP}
      FUSEKI_CLIENT_HOST: ${FUSEKI_IP}

      POSTGRES_HOST: ${DB_HOSTNAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRESS_PORT: ${POSTGRESS_PORT}

      CDB_USER: ${CDB_USER}
      CDB_PASSWORD: ${CDB_PASSWORD}
      CDB_HOST: ${CDB_HOST}
      CDB_DATABASE: ${CDB_DATABASE}

      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_SERVER: ${MAIL_SERVER}
    depends_on:
      - qualichain_backend
    networks:
      - config_qmediator


networks:
  config_qmediator:
    external: true


